# fly.toml app configuration file generated for gostick-gg on 2026-08-17T20:33:27-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'gostick-gg'
primary_region = 'sjc'

[build]
  dockerfile = 'Dockerfile'

[env]
  NODE_ENV = 'production'
  PORT = '5000'
  DATABASE_URL = 'file:/data/gostick.db'

[http_service]
  internal_port = 5000
  force_https = true
  auto_stop_machines = 'off'
  auto_start_machines = true

  [http_service.concurrency]
    type = 'connections'
    hard_limit = 1000
    soft_limit = 750

[[mounts]]
  source = 'gostick_data'
  destination = '/data'

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024
